# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19c44a8b840f4676c1d277b258f80425fced7114feb5faf01494ba1d96ce8e8821f0da4da508c11f1106b949383759c1ca4f21a0da1b0a8553660f19d720ad0e

test:
  secret_key_base: babbbf763791f774c6fb83f5a5094b4262cde81dece42bf88ffa4ddc2f4a349ebc836ef7b9428b0d6585ecb156c970b5d18849a7d0695ce097e2362bc4281fe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
